name: CI

on:
  create:
    branches: 
      - release/**
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'GravatarPK.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
   
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build $SOLUTION --configuration Release
      
    - name: Test
      run: dotnet test
      
    - name: Create the Package
      run: dotnet pack $SOLUTION --configuration Release
  
      
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: dotnet nuget push **\*.nupkg -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGETTOKEN}}
