name: Build and deploy package
on: 
  push:
    branchs:
      - main

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/chechout@main

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:'6.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Realese

    - name: Test
      run: dotnet test

    - name: Create the Package
      run: dotnet pack --configuration Realese

    - name: Publish
       run: dotnet nuget push "C:\Projects\PKG\Novapasta\GravatarPK/GravatarPK/bin/Release/GravatrPK.1.0.0.nupkg" -k ${{ secrets.NUGETTOKEN }} -s https://api.nuget.org/v3/index.json
