name: Build and deploy package
on: 
  push:
    branches:
      - main
    
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/chechout@main

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build with dotnet
      run: dotnet build --configuration Realese

    - name: Test
      run: dotnet test

    - name: Create the Package
      run: dotnet pack --configuration Realese

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
